systems-cs-pub-ro/iocla

- laborator/old/arm/1-install-toolchain/Makefile
- laborator/old/arm/1-install-toolchain/helloworld.asm
- laborator/old/arm/1-install-toolchain/install_toolchain.sh
- laborator/old/arm/2-mul-sum/Makefile
- laborator/old/arm/2-mul-sum/mul.asm
- laborator/old/arm/3-mem-addr/Makefile
- laborator/old/arm/3-mem-addr/mem.asm
- laborator/old/arm/4-flags/Makefile
- laborator/old/arm/4-flags/flags.asm
- laborator/old/arm/5-strings/Makefile
- laborator/old/arm/5-strings/strings.asm
Am adăugat în repository fișierele pentru laboratorul vechi de ARM, iar textul laboratorului pe [ocw](https://ocw.cs.pub.ro/courses/iocla/laboratoare/extra/laborator-arm). Probabil s-ar putea face să arate mai bine link-ul din sidebar pe ocw, eventual adăugată o categorie suplimentară. PR-ul rezolvă https://github.com/systems-cs-pub-ro/iocla/issues/13.
> Add old ARM lab files

- laborator/lab-11/1-2-loop-unrolling/Makefile
- laborator/lab-11/1-2-loop-unrolling/normal_loop.c
- laborator/lab-11/1-2-loop-unrolling/unrolled_loop.c
- laborator/lab-11/3-optimize/Makefile
- laborator/lab-11/3-optimize/optimize.c
- laborator/lab-11/4-binops/Makefile
- laborator/lab-11/4-binops/binops.c
- laborator/lab-11/5-profiling/Makefile
- laborator/lab-11/5-profiling/profile.asm
- laborator/lab-11/6-optimize-assembly/Makefile
- laborator/lab-11/6-optimize-assembly/main.c
- laborator/lab-11/6-optimize-assembly/optimize.asm
Signed-off-by: Darius Mihai <dariusmihaim@gmail.com>
> labs: Add content for lab 11

- laborator/lab-03/README.md
This will add a README.md file in laborator/lab-03
containing a the Markdown version for the 3rd laboratory
of IOCLA 2020.
> Lab03: Add Markdown version for lab-03 2020

- scripts/convert.py
- scripts/update-ocw.sh
this contains only scripts without github workflows
> created tools for github ocw integration

- laborator/content/stiva/README.md
- laborator/lab-08
Signed-off-by: Daniel Dinca <dincadaniel97@gmail.com>
> Lab-08 2021: Change symlink and lab number

- laborator/lab-10
Signed-off-by: Bianca Fodor <biancam.fodor@gmail.com>
> Lab-CASM: Change symlink

- laborator/content/rolul-registrelor-adresare/README.md
> Lab-06: Change lab number and add TIP note

- laborator/content/structuri-vectori-siruri/README.md
Signed-off-by: Darius Mihai <dariusmihaim@gmail.com>
> Lab-struct: Fix README hl and use ebp for stack

- laborator/content/toolchain-decompilare/demo/compiling_steps/Makefile
- laborator/content/toolchain-decompilare/demo/compiling_steps/hello-world.c
- laborator/content/toolchain-decompilare/demo/goto/Makefile
- laborator/content/toolchain-decompilare/demo/goto/goto.c
> Add demos for lab03.

- .github/workflows/main.yml
Add checkpatch workflow to run for every PR. #82 
> Add checkpatch workflow to run for every PR.

- COPYING.md
Add license for content and source code. Resolve #84 
> Add license for content and source code.

- laborator/content/introducere-asamblare/demo/Makefile
- laborator/content/introducere-asamblare/demo/instructions.asm
> Add demos for lab05.

- laborator/content/apel-functii/demo/call-function/Makefile
- laborator/content/apel-functii/demo/call-function/call-function-demo.asm
- laborator/content/apel-functii/demo/intro/Makefile
- laborator/content/apel-functii/demo/intro/intro-demo.asm
My personal demo for the lab 09 - call functions.
> Add demos for lab09.

- laborator/content/operatii-memorie-gdb/1-iterate/Makefile
- laborator/content/operatii-memorie-gdb/2-delete-first/Makefile
- laborator/content/operatii-memorie-gdb/3-pixels/Makefile
- laborator/content/operatii-memorie-gdb/4-find-max/Makefile
- laborator/content/operatii-memorie-gdb/7-pointers/Makefile
Some makefiles in lab-02 had wrong names
Signed-off-by: Robert Grancsa <robert.grancsa@stud.acs.upb.com>
> Fixed naming of compiled files

- laborator/content/stiva/demo/sum-n/.gitignore
- laborator/content/stiva/demo/sum-n/Makefile
- laborator/content/stiva/demo/sum-n/sum_n.asm
- laborator/content/stiva/demo/sum-n/sum_n_init.asm
- laborator/content/stiva/demo/sum-n/sum_n_interm.asm
> lab/stack: Add demo (sum-n) in assembly

- laborator/content/reprezentare-numere/demo/pointers/Makefile
- laborator/content/reprezentare-numere/demo/pointers/pointers-demo.c
> Add demos for lab01.

- laborator/content/reprezentare-numere/demo/bitmask/.gitignore
- laborator/content/reprezentare-numere/demo/bitmask/Makefile
- laborator/content/reprezentare-numere/demo/bitmask/bitmask.c
Add demo with bit numbering function.
> Review lab-01 (number representation)

- curs/chap-02-construire-programe/02-two-files/inc.c
- curs/chap-02-construire-programe/02-two-files/two.c
This improves understanding of which symbols are imported and which symbols are exported.
> chap-02: Add import / export comments

- curs/chap-01-prog/01-pointers/inspect_array.c
- curs/chap-01-prog/01-pointers/inspect_func.c
- curs/chap-01-prog/01-pointers/inspect_ptr.c
- curs/chap-01-prog/01-pointers/inspect_struct.c
Review demo source code for chapter 01.
> Review demos for chapter 01

- laborator/content/operatii-memorie-gdb/2-delete-first/delete-first.c
Added a comment hinting at a possible mistake in the declaration of s. 
Fixes #122
> lab/memory-gdb: Add comment about difference between char *s and char s[]

- laborator/content/rolul-registrelor-adresare/1-2-multiply/multiply.asm
- laborator/content/rolul-registrelor-adresare/3-4-sum-n/sum-n.asm
- laborator/content/rolul-registrelor-adresare/5-6-7-sum-array/sum-array.asm
- laborator/content/rolul-registrelor-adresare/8-divide/divide.asm
Merged: 
- multiply.asm lines 27-30
- sum_n.asm lines 23-26
- sum_array.asm lines 27-28
- divide.asm lines 34-35
> Merged multiple lines of PRINTF32 - fix #124

- laborator/content/introducere-asamblare/7-cf-of/Makefile
- laborator/content/introducere-asamblare/7-cf-of/cf-of.asm
- laborator/content/introducere-asamblare/7-cf-of/cf.asm
- laborator/content/introducere-asamblare/7-cf-of/of.asm
- laborator/content/introducere-asamblare/README.md
- laborator/content/introducere-asamblare/solution/7-cf-of/Makefile
- laborator/content/introducere-asamblare/solution/7-cf-of/cf-of.asm
- laborator/content/introducere-asamblare/solution/7-cf-of/cf.asm
- laborator/content/introducere-asamblare/solution/7-cf-of/of.asm
> lab/assembly-intro: Add CF vs OF example: Fixes #123

- laborator/content/introducere-asamblare/solutions/1-2-hello-world/Makefile
- laborator/content/introducere-asamblare/solutions/1-2-hello-world/hello_world.asm
- laborator/content/introducere-asamblare/solutions/3-grumpy-jumps/Makefile
- laborator/content/introducere-asamblare/solutions/3-grumpy-jumps/grumpy_jumps.asm
- laborator/content/introducere-asamblare/solutions/4-sets/Makefile
- laborator/content/introducere-asamblare/solutions/4-sets/sets.asm
- laborator/content/introducere-asamblare/solutions/5-min/Makefile
- laborator/content/introducere-asamblare/solutions/5-min/min.asm
- laborator/content/introducere-asamblare/solutions/6-fibonacci/Makefile
- laborator/content/introducere-asamblare/solutions/6-fibonacci/fibonacci.asm
> Solutions lab5

- laborator/content/toolchain-decompilare/README.md
This PR helps the students to install the `libcrypto.so.1.1` in case it's not present on their systems.
> Update README.md.- Install libcrypto.so

- laborator/content/operatii-memorie-gdb/demo/func-pointers/Makefile
- laborator/content/operatii-memorie-gdb/demo/func-pointers/func-pointers.c
- laborator/content/operatii-memorie-gdb/demo/pointers/Makefile
- laborator/content/operatii-memorie-gdb/demo/pointers/pointers.c
- laborator/content/operatii-memorie-gdb/demo/swap-strings/Makefile
- laborator/content/operatii-memorie-gdb/demo/swap-strings/swap-strings.c
> Add demos for lab02.

- laborator/content/rolul-registrelor-adresare/demo/addressing_memory/Makefile
- laborator/content/rolul-registrelor-adresare/demo/addressing_memory/addressing_memory.asm
- laborator/content/rolul-registrelor-adresare/demo/declaration/Makefile
- laborator/content/rolul-registrelor-adresare/demo/declaration/declaration.asm
- laborator/content/rolul-registrelor-adresare/demo/floating-point-exception/Makefile
- laborator/content/rolul-registrelor-adresare/demo/floating-point-exception/floating-point-exception.asm
- laborator/content/rolul-registrelor-adresare/demo/loop/Makefile
- laborator/content/rolul-registrelor-adresare/demo/loop/loop.asm
- laborator/content/rolul-registrelor-adresare/demo/multiply-divide/Makefile
- laborator/content/rolul-registrelor-adresare/demo/multiply-divide/multiply-divide.asm
> Add demos for lab06.
